/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaLand.ui;

import JavaLand.JA;
import JavaLand.util.FrameMonitor;

/**
 *
 * @author aladar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Singleton sub-windows
     */
    private NotepadFrame notepadFrame;
    private PaletteFrame paletteFrame;
    private AboutDialog aboutDialog;
    
    /**
     * Padding for statusLabel
     */
    private final String statusPad = "  ";
    
    /**
     * Creates new form MainJFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Java Land");
        FrameMonitor.registerFrame(this, MainFrame.class.getName(),
                this.getX(), this.getY(), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        utilityMenu = new javax.swing.JMenu();
        notepadMenuItem = new javax.swing.JMenuItem();
        paletteMenuItem = new javax.swing.JMenuItem();
        gameMenu = new javax.swing.JMenu();
        invadersMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        defaultsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        statusLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusLabel.setMaximumSize(new java.awt.Dimension(999999999, 999999999));
        statusLabel.setMinimumSize(new java.awt.Dimension(4, 25));

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenuBar.add(fileMenu);

        utilityMenu.setMnemonic('U');
        utilityMenu.setText("Utility");

        notepadMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        notepadMenuItem.setMnemonic('N');
        notepadMenuItem.setText("Notepad");
        notepadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadMenuItemActionPerformed(evt);
            }
        });
        utilityMenu.add(notepadMenuItem);

        paletteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        paletteMenuItem.setMnemonic('P');
        paletteMenuItem.setText("Palette");
        paletteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paletteMenuItemActionPerformed(evt);
            }
        });
        utilityMenu.add(paletteMenuItem);

        mainMenuBar.add(utilityMenu);

        gameMenu.setMnemonic('G');
        gameMenu.setText("Game");

        invadersMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        invadersMenuItem.setMnemonic('I');
        invadersMenuItem.setText("Invaders");
        gameMenu.add(invadersMenuItem);

        mainMenuBar.add(gameMenu);

        optionsMenu.setMnemonic('O');
        optionsMenu.setText("Options");

        defaultsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        defaultsMenuItem.setMnemonic('D');
        defaultsMenuItem.setText("Defaults");
        defaultsMenuItem.setToolTipText("");
        defaultsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultsMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(defaultsMenuItem);

        mainMenuBar.add(optionsMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        if (aboutDialog == null) 
            aboutDialog = new AboutDialog(this, false); // or rootPaneCheckingEnabled
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void paletteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paletteMenuItemActionPerformed
        if (paletteFrame == null)
            paletteFrame = new PaletteFrame();
        paletteFrame.setVisible(true);
    }//GEN-LAST:event_paletteMenuItemActionPerformed

    private void defaultsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultsMenuItemActionPerformed
        //----------------------------------------------------------------------
        // MainFrame
        FrameMonitor.setDefaults(this, MainFrame.class.getName());

        //----------------------------------------------------------------------
        // Notepad
        var dispose = false;
        if (notepadFrame == null) {
            notepadFrame = new NotepadFrame();
            dispose = true;
        }
        FrameMonitor.setDefaults(notepadFrame, NotepadFrame.class.getName());
        if (dispose)
            notepadFrame.dispose();

        //----------------------------------------------------------------------
        // Palette
        dispose = false;
        if (paletteFrame == null) {
            paletteFrame = new PaletteFrame();
            dispose = true;
        }
        FrameMonitor.setDefaults(paletteFrame, PaletteFrame.class.getName());
        if (dispose)
            paletteFrame.dispose();
    }//GEN-LAST:event_defaultsMenuItemActionPerformed

    private void notepadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadMenuItemActionPerformed
        if (notepadFrame == null)
            notepadFrame = new NotepadFrame();
        notepadFrame.setVisible(true);
    }//GEN-LAST:event_notepadMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem defaultsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem invadersMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem notepadMenuItem;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem paletteMenuItem;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JMenu utilityMenu;
    // End of variables declaration//GEN-END:variables
}
