/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaLand.ui;

import JavaLand.JA;
import JavaLand.util.FrameMonitor;

/**
 *
 * @author aladar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Java Land");
        FrameMonitor.registerFrame(this, MainFrame.class.getName(),
                this.getX(), this.getY(), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        utilityMenu = new javax.swing.JMenu();
        notepadMenuItem = new javax.swing.JMenuItem();
        paletteMenuItem = new javax.swing.JMenuItem();
        gameMenu = new javax.swing.JMenu();
        invadersMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        DefaultsMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('F');
        fileMenu.setText("File");

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        mainMenuBar.add(fileMenu);

        utilityMenu.setMnemonic('U');
        utilityMenu.setText("Utility");

        notepadMenuItem.setMnemonic('N');
        notepadMenuItem.setText("Notepad");
        utilityMenu.add(notepadMenuItem);

        paletteMenuItem.setMnemonic('P');
        paletteMenuItem.setText("Palette");
        paletteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paletteMenuItemActionPerformed(evt);
            }
        });
        utilityMenu.add(paletteMenuItem);

        mainMenuBar.add(utilityMenu);

        gameMenu.setMnemonic('G');
        gameMenu.setText("Game");

        invadersMenuItem.setMnemonic('I');
        invadersMenuItem.setText("Invaders");
        gameMenu.add(invadersMenuItem);

        mainMenuBar.add(gameMenu);

        optionsMenu.setMnemonic('O');
        optionsMenu.setText("Options");

        DefaultsMenuItem.setMnemonic('D');
        DefaultsMenuItem.setText("Defaults");
        DefaultsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultsMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(DefaultsMenuItem);

        mainMenuBar.add(optionsMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMenuItem.setMnemonic('A');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenuBar.add(helpMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        AboutDialog about = new AboutDialog(this, false); // or rootPaneCheckingEnabled
        about.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void paletteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paletteMenuItemActionPerformed
        PaletteFrame palette = new PaletteFrame();
        palette.setVisible(true);
    }//GEN-LAST:event_paletteMenuItemActionPerformed

    private void DefaultsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultsMenuItemActionPerformed
        FrameMonitor.setDefaults(this, MainFrame.class.getName());

        // TODO: think about generally not recreating and disposing child frames
        // each time, but only hiding them
        PaletteFrame palette = new PaletteFrame();
        FrameMonitor.setDefaults(palette, PaletteFrame.class.getName());
        palette.dispose();
    }//GEN-LAST:event_DefaultsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DefaultsMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem invadersMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem notepadMenuItem;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem paletteMenuItem;
    private javax.swing.JMenu utilityMenu;
    // End of variables declaration//GEN-END:variables
}
