/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaLand.ui;

import JavaLand.JA;
import JavaLand.util.ContainerMonitor;
import javax.swing.JDesktopPane;

/**
 *
 * @author aladar
 */
public class PaletteInternalFrame extends javax.swing.JInternalFrame {

    //==========================================================================
    // Singleton
    //==========================================================================
    /**
     * Creates new form PaletteInternalFrame
     */
    private PaletteInternalFrame() {
        initComponents();
        ContainerMonitor.registerContainer(this, PaletteInternalFrame.class.getName(),
                this.getX(), this.getY(), this.getWidth(), this.getHeight());
    }
    
    public static PaletteInternalFrame getInstance() {
        return PaletteInternalFrameHolder.INSTANCE;
    }
    
    private static class PaletteInternalFrameHolder {
        private static final PaletteInternalFrame INSTANCE = new PaletteInternalFrame();
    }

    //==========================================================================        
    // Dialogs opened from this JInternalFrame need this.
    // Invoke setMainFrame() just after calling the constructor.
    //==========================================================================        
    private MainFrame mainFrame;
    
    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    //==========================================================================
    // Desktop
    //==========================================================================
    private JDesktopPane desktop;
    
    public void setDesktop(JDesktopPane desktop) {
        this.desktop = desktop;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Palette");
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        closedOrHidden();
        // Focus back
        mainFrame.lastFocus.pop();
        if (mainFrame.lastFocus.size() > 0) {
            mainFrame.show(mainFrame.lastFocus.getLast());
        } 
    }//GEN-LAST:event_formComponentHidden

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        closedOrHidden();
    }//GEN-LAST:event_formInternalFrameClosed

    private void closedOrHidden() {
        // When necessary...
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
